name: Django CI/CD

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint the code using Flake8 and Black
      - name: Run Flake8 (Linting)
        run: flake8 .

      - name: Run Black (Code Formatting)
        run: black --check .

      # Step 5: Run tests and generate a coverage report
      - name: Run Tests
        run: |
          coverage run manage.py test
          coverage report
